!io
version: 0
type: xml
param_root: !list
  objects:
    CommonData: !obj
      UpperLimitHight: 1.27999997
      LowerLimitHight: 0.0700000003
  lists:
    ImpulseParamList: !list
      objects:
        ImpulseParam_Default: !obj
          FileName: !str64 Enemy_SiteBoss_Spear_Default
        ImpulseParam_Sword: !obj
          FileName: !str64 Enemy_SiteBoss_Spear_Sword
        ImpulseParam_LargeSword: !obj
          FileName: !str64 Enemy_SiteBoss_Spear_LargeSword
        ImpulseParam_Spear: !obj
          FileName: !str64 Enemy_SiteBoss_Spear_Spear
        ImpulseParam_Arrow: !obj
          FileName: !str64 Enemy_SiteBoss_Spear_Arrow
        ImpulseParam_Bomb: !obj
          FileName: !str64 Enemy_SiteBoss_Spear_Bomb
        ImpulseParam_ShockWave: !obj
          FileName: !str64 Enemy_SiteBoss_Spear_ShockWave
        ImpulseParam_HeadShot: !obj
          FileName: !str64 Enemy_SiteBoss_Spear_HeadShot
      lists: {}
    BodyParamList: !list
      objects:
        BodyParam_0: !obj
          RigidName: !str64 Ragdoll_Arm_1_L
          FrictionScale: 0.600000024
          BuoyancyScale: 0.0299999993
        BodyParam_1: !obj
          RigidName: !str64 Ragdoll_Arm_1_R
          FrictionScale: 0.600000024
          BuoyancyScale: 0.0299999993
        BodyParam_2: !obj
          RigidName: !str64 Ragdoll_Arm_2_L
          FrictionScale: 0.600000024
          BuoyancyScale: 0.00999999978
        BodyParam_3: !obj
          RigidName: !str64 Ragdoll_Arm_2_R
          FrictionScale: 0.600000024
          BuoyancyScale: 0.00999999978
        BodyParam_4: !obj
          RigidName: !str64 Ragdoll_Head
          FrictionScale: 0.600000024
          BuoyancyScale: 0.00999999978
        BodyParam_5: !obj
          RigidName: !str64 Ragdoll_Neck
          FrictionScale: 0.600000024
          BuoyancyScale: 0.0299999993
        BodyParam_6: !obj
          RigidName: !str64 Ragdoll_Spine_1
          FrictionScale: 0.600000024
          BuoyancyScale: 0.0599999987
        BodyParam_7: !obj
          RigidName: !str64 Ragdoll_Spine_2
          FrictionScale: 0.600000024
          BuoyancyScale: 0.0700000003
        BodyParam_8: !obj
          RigidName: !str64 Ragdoll_Spine_3
          FrictionScale: 0.600000024
          BuoyancyScale: 0.0799999982
        BodyParam_9: !obj
          RigidName: !str64 Ragdoll_Spine_4
          FrictionScale: 0.600000024
          BuoyancyScale: 0.100000001
        BodyParam_10: !obj
          RigidName: !str64 Ragdoll_Waist
          FrictionScale: 0.600000024
          BuoyancyScale: 0.00400000019
        BodyParam_11: !obj
          RigidName: !str64 Ragdoll_Wrist_L
          FrictionScale: 0.600000024
          BuoyancyScale: 0.00999999978
        BodyParam_12: !obj
          RigidName: !str64 Ragdoll_Wrist_R
          FrictionScale: 0.600000024
          BuoyancyScale: 0.00999999978
      lists: {}
