!io
version: 0
type: xml
param_root: !list
  objects:
    CommonData: !obj
      UpperLimitHight: 1.79999995
      LowerLimitHight: -3.0
  lists:
    ImpulseParamList: !list
      objects:
        ImpulseParam_Default: !obj
          FileName: !str64 Enemy_Giant_Default
        ImpulseParam_Sword: !obj
          FileName: !str64 Enemy_Giant_Sword
        ImpulseParam_LargeSword: !obj
          FileName: !str64 Enemy_Giant_LargeSword
        ImpulseParam_Spear: !obj
          FileName: !str64 Enemy_Giant_Spear
        ImpulseParam_Arrow: !obj
          FileName: !str64 Enemy_Giant_Arrow
        ImpulseParam_Bomb: !obj
          FileName: !str64 Enemy_Giant_Bomb
        ImpulseParam_HeadShot: !obj
          FileName: !str64 Enemy_Giant_HeadShot
        ImpulseParam_ShockWave: !obj
          FileName: !str64 Enemy_Giant_ShockWave
      lists: {}
    BodyParamList: !list
      objects:
        BodyParam_0: !obj
          RigidName: !str64 Ragdoll_Ankle_L
          FrictionScale: 0.75
          BuoyancyScale: 0.00100000005
        BodyParam_1: !obj
          RigidName: !str64 Ragdoll_Ankle_R
          FrictionScale: 0.75
          BuoyancyScale: 0.00100000005
        BodyParam_2: !obj
          RigidName: !str64 Ragdoll_Arm_1_L
          FrictionScale: 0.5
          BuoyancyScale: 0.00100000005
        BodyParam_3: !obj
          RigidName: !str64 Ragdoll_Arm_1_R
          FrictionScale: 0.5
          BuoyancyScale: 0.00100000005
        BodyParam_4: !obj
          RigidName: !str64 Ragdoll_Arm_2_L
          FrictionScale: 0.5
          BuoyancyScale: 0.00100000005
        BodyParam_5: !obj
          RigidName: !str64 Ragdoll_Arm_2_R
          FrictionScale: 0.5
          BuoyancyScale: 0.00100000005
        BodyParam_6: !obj
          RigidName: !str64 Ragdoll_Clavicle_L
          FrictionScale: 1.0
          BuoyancyScale: 1.0
        BodyParam_7: !obj
          RigidName: !str64 Ragdoll_Clavicle_R
          FrictionScale: 1.0
          BuoyancyScale: 1.0
        BodyParam_8: !obj
          RigidName: !str64 Ragdoll_Head
          FrictionScale: 1.0
          BuoyancyScale: 0.00100000005
        BodyParam_9: !obj
          RigidName: !str64 Ragdoll_Leg_1_L
          FrictionScale: 0.75
          BuoyancyScale: 0.00100000005
        BodyParam_10: !obj
          RigidName: !str64 Ragdoll_Leg_1_R
          FrictionScale: 0.75
          BuoyancyScale: 0.00100000005
        BodyParam_11: !obj
          RigidName: !str64 Ragdoll_Leg_2_L
          FrictionScale: 0.75
          BuoyancyScale: 0.00100000005
        BodyParam_12: !obj
          RigidName: !str64 Ragdoll_Leg_2_R
          FrictionScale: 0.75
          BuoyancyScale: 0.00100000005
        BodyParam_13: !obj
          RigidName: !str64 Ragdoll_Skl_Root
          FrictionScale: 1.0
          BuoyancyScale: 0.00100000005
        BodyParam_14: !obj
          RigidName: !str64 Ragdoll_Spine_1
          FrictionScale: 1.0
          BuoyancyScale: 0.00100000005
        BodyParam_15: !obj
          RigidName: !str64 Ragdoll_Wrist_L
          FrictionScale: 0.5
          BuoyancyScale: 0.00100000005
        BodyParam_16: !obj
          RigidName: !str64 Ragdoll_Wrist_R
          FrictionScale: 0.5
          BuoyancyScale: 0.00100000005
      lists: {}
