!io
version: 0
type: xml
param_root: !list
  objects:
    CommonData: !obj
      UpperLimitHight: 0.200000003
      LowerLimitHight: -0.25
  lists:
    ImpulseParamList: !list
      objects:
        ImpulseParam_Default: !obj
          FileName: !str64 Dummy
        ImpulseParam_Sword: !obj
          FileName: !str64 Dummy
        ImpulseParam_LargeSword: !obj
          FileName: !str64 Dummy
        ImpulseParam_Spear: !obj
          FileName: !str64 Dummy
        ImpulseParam_Arrow: !obj
          FileName: !str64 Dummy
        ImpulseParam_Bomb: !obj
          FileName: !str64 Dummy
        ImpulseParam_HeadShot: !obj
          FileName: !str64 Dummy
        ImpulseParam_ShockWave: !obj
          FileName: !str64 Dummy
      lists: {}
    BodyParamList: !list
      objects:
        BodyParam_0: !obj
          RigidName: !str64 Ragdoll_Ankle_L
          FrictionScale: 0.75
          BuoyancyScale: 0.400000006
        BodyParam_1: !obj
          RigidName: !str64 Ragdoll_Ankle_R
          FrictionScale: 0.75
          BuoyancyScale: 0.400000006
        BodyParam_2: !obj
          RigidName: !str64 Ragdoll_Arm_1_L
          FrictionScale: 0.5
          BuoyancyScale: 0.400000006
        BodyParam_3: !obj
          RigidName: !str64 Ragdoll_Arm_1_R
          FrictionScale: 0.5
          BuoyancyScale: 0.400000006
        BodyParam_4: !obj
          RigidName: !str64 Ragdoll_Head
          FrictionScale: 1.0
          BuoyancyScale: 0.400000006
        BodyParam_5: !obj
          RigidName: !str64 Ragdoll_Leg_1_L
          FrictionScale: 0.75
          BuoyancyScale: 0.400000006
        BodyParam_6: !obj
          RigidName: !str64 Ragdoll_Leg_1_R
          FrictionScale: 0.75
          BuoyancyScale: 0.400000006
        BodyParam_7: !obj
          RigidName: !str64 Ragdoll_Leg_2_L
          FrictionScale: 0.75
          BuoyancyScale: 0.400000006
        BodyParam_8: !obj
          RigidName: !str64 Ragdoll_Leg_2_R
          FrictionScale: 0.75
          BuoyancyScale: 0.400000006
        BodyParam_9: !obj
          RigidName: !str64 Ragdoll_Neck_1
          FrictionScale: 1.0
          BuoyancyScale: 0.400000006
        BodyParam_10: !obj
          RigidName: !str64 Ragdoll_Skl_Root
          FrictionScale: 1.0
          BuoyancyScale: 0.400000006
        BodyParam_11: !obj
          RigidName: !str64 Ragdoll_Spine_1
          FrictionScale: 1.0
          BuoyancyScale: 0.400000006
        BodyParam_12: !obj
          RigidName: !str64 Ragdoll_Toe_1_BL
          FrictionScale: 1.0
          BuoyancyScale: 0.400000006
        BodyParam_13: !obj
          RigidName: !str64 Ragdoll_Toe_1_BR
          FrictionScale: 1.0
          BuoyancyScale: 0.400000006
        BodyParam_14: !obj
          RigidName: !str64 Ragdoll_Toe_1_FL
          FrictionScale: 1.0
          BuoyancyScale: 0.400000006
        BodyParam_15: !obj
          RigidName: !str64 Ragdoll_Toe_1_FR
          FrictionScale: 1.0
          BuoyancyScale: 0.400000006
        BodyParam_16: !obj
          RigidName: !str64 Ragdoll_Wrist_L
          FrictionScale: 0.5
          BuoyancyScale: 0.400000006
        BodyParam_17: !obj
          RigidName: !str64 Ragdoll_Wrist_R
          FrictionScale: 0.5
          BuoyancyScale: 0.400000006
      lists: {}
