!io
version: 0
type: xml
param_root: !list
  objects:
    CommonData: !obj
      UpperLimitHight: 0.150000006
      LowerLimitHight: -0.529999971
  lists:
    ImpulseParamList: !list
      objects:
        ImpulseParam_Default: !obj
          FileName: !str64 Assassin_Soldier_Default
        ImpulseParam_Sword: !obj
          FileName: !str64 Assassin_Soldier_Sword
        ImpulseParam_LargeSword: !obj
          FileName: !str64 Assassin_Soldier_LargeSword
        ImpulseParam_Spear: !obj
          FileName: !str64 Assassin_Soldier_Spear
        ImpulseParam_Arrow: !obj
          FileName: !str64 Assassin_Soldier_Arrow
        ImpulseParam_Bomb: !obj
          FileName: !str64 Assassin_Soldier_Bomb
        ImpulseParam_HeadShot: !obj
          FileName: !str64 Assassin_Soldier_HeadShot
        ImpulseParam_ShockWave: !obj
          FileName: !str64 Assassin_Soldier_ShockWave
        ImpulseParam_Gust: !obj
          FileName: !str64 Assassin_Soldier_Gust
      lists: {}
    BodyParamList: !list
      objects:
        BodyParam_0: !obj
          RigidName: !str64 Ragdoll_Ankle_L
          FrictionScale: 0.75
          BuoyancyScale: 0.5
        BodyParam_1: !obj
          RigidName: !str64 Ragdoll_Ankle_R
          FrictionScale: 0.75
          BuoyancyScale: 0.5
        BodyParam_2: !obj
          RigidName: !str64 Ragdoll_Arm_1_L
          FrictionScale: 0.5
          BuoyancyScale: 1.0
        BodyParam_3: !obj
          RigidName: !str64 Ragdoll_Arm_1_R
          FrictionScale: 0.5
          BuoyancyScale: 1.0
        BodyParam_4: !obj
          RigidName: !str64 Ragdoll_Arm_2_L
          FrictionScale: 0.5
          BuoyancyScale: 0.5
        BodyParam_5: !obj
          RigidName: !str64 Ragdoll_Arm_2_R
          FrictionScale: 0.5
          BuoyancyScale: 0.5
        BodyParam_6: !obj
          RigidName: !str64 Ragdoll_Head
          FrictionScale: 0.800000012
          BuoyancyScale: 0.400000006
        BodyParam_7: !obj
          RigidName: !str64 Ragdoll_Leg_1_L
          FrictionScale: 0.75
          BuoyancyScale: 1.0
        BodyParam_8: !obj
          RigidName: !str64 Ragdoll_Leg_1_R
          FrictionScale: 0.75
          BuoyancyScale: 1.0
        BodyParam_9: !obj
          RigidName: !str64 Ragdoll_Leg_2_L
          FrictionScale: 0.75
          BuoyancyScale: 0.400000006
        BodyParam_10: !obj
          RigidName: !str64 Ragdoll_Leg_2_R
          FrictionScale: 0.75
          BuoyancyScale: 0.400000006
        BodyParam_11: !obj
          RigidName: !str64 Ragdoll_Skl_Root
          FrictionScale: 0.699999988
          BuoyancyScale: 2.0
        BodyParam_12: !obj
          RigidName: !str64 Ragdoll_Spine_1
          FrictionScale: 0.699999988
          BuoyancyScale: 1.0
        BodyParam_13: !obj
          RigidName: !str64 Ragdoll_Wrist_L
          FrictionScale: 0.5
          BuoyancyScale: 0.5
        BodyParam_14: !obj
          RigidName: !str64 Ragdoll_Wrist_R
          FrictionScale: 0.5
          BuoyancyScale: 0.5
      lists: {}
