!io
version: 0
type: xml
param_root: !list
  objects: {}
  lists:
    ConfigRoot: !list
      objects:
        AttackTypeImpulseData: !obj
          ImpulseUseRate: 0.5
          ImpulsePower: 1200.0
          LargeAttackRate: 5.0
          BlastOffAttackRateSmall: 4.0
          BlastOffAttackRateLarge: 6.0
          SpecialAttackRate: 10.0
      lists:
        ImpactImpulseInfo01: !list
          objects: {}
          lists:
            PartImpulseInfo01: !list
              objects:
                ReceiveObj01: !obj
                  TypeName: !str64 Ragdoll_Head
                  DivideFlag: true
                  ImpulseRate: 0.5
                  DivideRate: 0.5
                ReceiveObj02: !obj
                  TypeName: !str64 Ragdoll_Head
                  DivideFlag: true
                  ImpulseRate: 0.5
                  DivideRate: 0.5
                ReceiveObj03: !obj
                  TypeName: !str64 ''
                  DivideFlag: false
                  ImpulseRate: 1.0
                  DivideRate: 0.5
                ImpulseObj01: !obj
                  TypeName: !str64 Ragdoll_Head
                  UseFlag: true
                  AttackVector: !vec3 [0.0, 0.349999994, -0.25]
                  AttackPoint: !vec3 [0.0, 0.0, 0.0]
                  ImpulsePower: 5000.0
                ImpulseObj02: !obj
                  TypeName: !str64 Ragdoll_Spine_1
                  UseFlag: true
                  AttackVector: !vec3 [0.0, 0.349999994, -0.25]
                  AttackPoint: !vec3 [0.0, 0.0, 0.0]
                  ImpulsePower: 3500.0
                ImpulseObj03: !obj
                  TypeName: !str64 ''
                  UseFlag: false
                  AttackVector: !vec3 [0.0, 0.0, 0.0]
                  AttackPoint: !vec3 [0.0, 0.0, 0.0]
                  ImpulsePower: 0.100000001
                ImpulseObj04: !obj
                  TypeName: !str64 ''
                  UseFlag: false
                  AttackVector: !vec3 [0.0, 0.0, 0.0]
                  AttackPoint: !vec3 [0.0, 0.0, 0.0]
                  ImpulsePower: 0.100000001
                ImpulseObj05: !obj
                  TypeName: !str64 ''
                  UseFlag: false
                  AttackVector: !vec3 [0.0, 0.0, 0.0]
                  AttackPoint: !vec3 [0.0, 0.0, 0.0]
                  ImpulsePower: 0.100000001
                PartImpulseData: !obj
                  IsUseReceiveImpulse: true
                  IsUseFixedImpulse: true
              lists: {}
            PartImpulseInfo02: !list
              objects:
                ReceiveObj01: !obj
                  TypeName: !str64 Ragdoll_Spine_1
                  DivideFlag: true
                  ImpulseRate: 0.5
                  DivideRate: 0.5
                ReceiveObj02: !obj
                  TypeName: !str64 Ragdoll_Skl_Root
                  DivideFlag: true
                  ImpulseRate: 0.5
                  DivideRate: 0.5
                ReceiveObj03: !obj
                  TypeName: !str64 ''
                  DivideFlag: false
                  ImpulseRate: 1.0
                  DivideRate: 0.5
                ImpulseObj01: !obj
                  TypeName: !str64 Ragdoll_Head
                  UseFlag: true
                  AttackVector: !vec3 [0.0, -0.100000001, 0.0219999999]
                  AttackPoint: !vec3 [0.0, 0.0, 0.0]
                  ImpulsePower: 1500.0
                ImpulseObj02: !obj
                  TypeName: !str64 Ragdoll_Spine_2
                  UseFlag: true
                  AttackVector: !vec3 [0.0, 0.460000008, -1.0]
                  AttackPoint: !vec3 [0.0, 0.0, 0.0]
                  ImpulsePower: 5000.0
                ImpulseObj03: !obj
                  TypeName: !str64 ''
                  UseFlag: false
                  AttackVector: !vec3 [0.0500000007, 0.0, 1.0]
                  AttackPoint: !vec3 [0.0, 0.0, 0.0]
                  ImpulsePower: 250.0
                ImpulseObj04: !obj
                  TypeName: !str64 ''
                  UseFlag: false
                  AttackVector: !vec3 [-0.0500000007, 0.0, 1.0]
                  AttackPoint: !vec3 [0.0, 0.0, 0.0]
                  ImpulsePower: 250.0
                ImpulseObj05: !obj
                  TypeName: !str64 ''
                  UseFlag: false
                  AttackVector: !vec3 [0.0, 0.0, 0.0]
                  AttackPoint: !vec3 [0.0, 0.0, 0.0]
                  ImpulsePower: 0.100000001
                PartImpulseData: !obj
                  IsUseReceiveImpulse: true
                  IsUseFixedImpulse: true
              lists: {}
            PartImpulseInfo03: !list
              objects:
                ReceiveObj01: !obj
                  TypeName: !str64 Ragdoll_Skl_Root
                  DivideFlag: true
                  ImpulseRate: 0.5
                  DivideRate: 0.5
                ReceiveObj02: !obj
                  TypeName: !str64 Ragdoll_Skl_Root
                  DivideFlag: true
                  ImpulseRate: 0.5
                  DivideRate: 0.5
                ReceiveObj03: !obj
                  TypeName: !str64 ''
                  DivideFlag: false
                  ImpulseRate: 1.0
                  DivideRate: 0.5
                ImpulseObj01: !obj
                  TypeName: !str64 Ragdoll_Skl_Root
                  UseFlag: true
                  AttackVector: !vec3 [0.0, -1.0, -1.0]
                  AttackPoint: !vec3 [0.0, 0.0, 0.0]
                  ImpulsePower: 2500.0
                ImpulseObj02: !obj
                  TypeName: !str64 ''
                  UseFlag: false
                  AttackVector: !vec3 [0.0, 0.0, -1.0]
                  AttackPoint: !vec3 [0.0, 0.0, 0.0]
                  ImpulsePower: 2000.0
                ImpulseObj03: !obj
                  TypeName: !str64 ''
                  UseFlag: false
                  AttackVector: !vec3 [0.0, 0.75, 0.0]
                  AttackPoint: !vec3 [0.0, 0.0, 0.0]
                  ImpulsePower: 3500.0
                ImpulseObj04: !obj
                  TypeName: !str64 ''
                  UseFlag: false
                  AttackVector: !vec3 [0.0, 1.0, -0.162]
                  AttackPoint: !vec3 [0.0, 0.0, 0.0]
                  ImpulsePower: 800.0
                ImpulseObj05: !obj
                  TypeName: !str64 ''
                  UseFlag: false
                  AttackVector: !vec3 [0.0, 0.0, 0.0]
                  AttackPoint: !vec3 [0.0, 0.0, 0.0]
                  ImpulsePower: 0.100000001
                PartImpulseData: !obj
                  IsUseReceiveImpulse: true
                  IsUseFixedImpulse: true
              lists: {}
        ImpactImpulseInfo02: !list
          objects: {}
          lists:
            PartImpulseInfo01: !list
              objects:
                ReceiveObj01: !obj
                  TypeName: !str64 Ragdoll_Head
                  DivideFlag: true
                  ImpulseRate: 0.5
                  DivideRate: 0.5
                ReceiveObj02: !obj
                  TypeName: !str64 Ragdoll_Head
                  DivideFlag: true
                  ImpulseRate: 0.5
                  DivideRate: 0.5
                ReceiveObj03: !obj
                  TypeName: !str64 ''
                  DivideFlag: false
                  ImpulseRate: 1.0
                  DivideRate: 0.5
                ImpulseObj01: !obj
                  TypeName: !str64 Ragdoll_Head
                  UseFlag: true
                  AttackVector: !vec3 [0.0, 0.349999994, -0.25]
                  AttackPoint: !vec3 [0.0, 0.0, 0.0]
                  ImpulsePower: 5000.0
                ImpulseObj02: !obj
                  TypeName: !str64 Ragdoll_Spine_1
                  UseFlag: true
                  AttackVector: !vec3 [0.0, 0.349999994, -0.25]
                  AttackPoint: !vec3 [0.0, 0.0, 0.0]
                  ImpulsePower: 3500.0
                ImpulseObj03: !obj
                  TypeName: !str64 Ragdoll_Spine_1
                  UseFlag: true
                  AttackVector: !vec3 [0.0, 1.0, -0.349999994]
                  AttackPoint: !vec3 [0.0, 0.0, 0.0]
                  ImpulsePower: 7500.0
                ImpulseObj04: !obj
                  TypeName: !str64 ''
                  UseFlag: false
                  AttackVector: !vec3 [0.0, 0.0, 0.0]
                  AttackPoint: !vec3 [0.0, 0.0, 0.0]
                  ImpulsePower: 0.100000001
                ImpulseObj05: !obj
                  TypeName: !str64 ''
                  UseFlag: false
                  AttackVector: !vec3 [0.0, 0.0, 0.0]
                  AttackPoint: !vec3 [0.0, 0.0, 0.0]
                  ImpulsePower: 0.100000001
                PartImpulseData: !obj
                  IsUseReceiveImpulse: true
                  IsUseFixedImpulse: true
              lists: {}
            PartImpulseInfo02: !list
              objects:
                ReceiveObj01: !obj
                  TypeName: !str64 Ragdoll_Spine_1
                  DivideFlag: true
                  ImpulseRate: 0.5
                  DivideRate: 0.5
                ReceiveObj02: !obj
                  TypeName: !str64 Ragdoll_Skl_Root
                  DivideFlag: true
                  ImpulseRate: 0.5
                  DivideRate: 0.5
                ReceiveObj03: !obj
                  TypeName: !str64 ''
                  DivideFlag: false
                  ImpulseRate: 1.0
                  DivideRate: 0.5
                ImpulseObj01: !obj
                  TypeName: !str64 Ragdoll_Head
                  UseFlag: true
                  AttackVector: !vec3 [0.0, -0.100000001, 0.0219999999]
                  AttackPoint: !vec3 [0.0, 0.0, 0.0]
                  ImpulsePower: 1500.0
                ImpulseObj02: !obj
                  TypeName: !str64 Ragdoll_Spine_2
                  UseFlag: true
                  AttackVector: !vec3 [0.0, 0.460000008, -1.0]
                  AttackPoint: !vec3 [0.0, 0.0, 0.0]
                  ImpulsePower: 5000.0
                ImpulseObj03: !obj
                  TypeName: !str64 Ragdoll_Spine_1
                  UseFlag: true
                  AttackVector: !vec3 [0.0, 1.0, -0.349999994]
                  AttackPoint: !vec3 [0.0, 0.0, 0.0]
                  ImpulsePower: 7500.0
                ImpulseObj04: !obj
                  TypeName: !str64 ''
                  UseFlag: false
                  AttackVector: !vec3 [-0.0500000007, 0.0, 1.0]
                  AttackPoint: !vec3 [0.0, 0.0, 0.0]
                  ImpulsePower: 250.0
                ImpulseObj05: !obj
                  TypeName: !str64 ''
                  UseFlag: false
                  AttackVector: !vec3 [0.0, 0.0, 0.0]
                  AttackPoint: !vec3 [0.0, 0.0, 0.0]
                  ImpulsePower: 0.100000001
                PartImpulseData: !obj
                  IsUseReceiveImpulse: true
                  IsUseFixedImpulse: true
              lists: {}
            PartImpulseInfo03: !list
              objects:
                ReceiveObj01: !obj
                  TypeName: !str64 Ragdoll_Skl_Root
                  DivideFlag: true
                  ImpulseRate: 0.5
                  DivideRate: 0.5
                ReceiveObj02: !obj
                  TypeName: !str64 Ragdoll_Skl_Root
                  DivideFlag: true
                  ImpulseRate: 0.5
                  DivideRate: 0.5
                ReceiveObj03: !obj
                  TypeName: !str64 ''
                  DivideFlag: false
                  ImpulseRate: 1.0
                  DivideRate: 0.5
                ImpulseObj01: !obj
                  TypeName: !str64 Ragdoll_Skl_Root
                  UseFlag: true
                  AttackVector: !vec3 [0.0, -1.0, -1.0]
                  AttackPoint: !vec3 [0.0, 0.0, 0.0]
                  ImpulsePower: 2500.0
                ImpulseObj02: !obj
                  TypeName: !str64 Ragdoll_Skl_Root
                  UseFlag: true
                  AttackVector: !vec3 [0.0, -0.00999999978, -0.810000002]
                  AttackPoint: !vec3 [0.0, 0.0, 0.0]
                  ImpulsePower: 7500.0
                ImpulseObj03: !obj
                  TypeName: !str64 ''
                  UseFlag: false
                  AttackVector: !vec3 [0.0, 0.75, 0.0]
                  AttackPoint: !vec3 [0.0, 0.0, 0.0]
                  ImpulsePower: 3500.0
                ImpulseObj04: !obj
                  TypeName: !str64 ''
                  UseFlag: false
                  AttackVector: !vec3 [0.0, 1.0, -0.162]
                  AttackPoint: !vec3 [0.0, 0.0, 0.0]
                  ImpulsePower: 800.0
                ImpulseObj05: !obj
                  TypeName: !str64 ''
                  UseFlag: false
                  AttackVector: !vec3 [0.0, 0.0, 0.0]
                  AttackPoint: !vec3 [0.0, 0.0, 0.0]
                  ImpulsePower: 0.100000001
                PartImpulseData: !obj
                  IsUseReceiveImpulse: true
                  IsUseFixedImpulse: true
              lists: {}
