!io
version: 0
type: xml
param_root: !list
  objects: {}
  lists:
    ConfigRoot: !list
      objects:
        AttackTypeImpulseData: !obj
          ImpulseUseRate: 0.349999994
          ImpulsePower: 1200.0
          LargeAttackRate: 2.5
          BlastOffAttackRateSmall: 3.0
          BlastOffAttackRateLarge: 3.0
          SpecialAttackRate: 4.0
      lists:
        ImpactImpulseInfo01: !list
          objects: {}
          lists:
            PartImpulseInfo01: !list
              objects:
                ReceiveObj01: !obj
                  TypeName: !str64 Ragdoll_Head
                  DivideFlag: false
                  ImpulseRate: 1.0
                  DivideRate: 0.5
                ReceiveObj02: !obj
                  TypeName: !str64 Ragdoll_Head
                  DivideFlag: false
                  ImpulseRate: 1.0
                  DivideRate: 0.5
                ReceiveObj03: !obj
                  TypeName: !str64 Ragdoll_Head
                  DivideFlag: false
                  ImpulseRate: 1.0
                  DivideRate: 0.5
                ImpulseObj01: !obj
                  TypeName: !str64 Ragdoll_Head
                  UseFlag: true
                  AttackVector: !vec3 [0.0, 1.0, -1.0]
                  AttackPoint: !vec3 [0.0, 0.0, 0.0]
                  ImpulsePower: 5000.0
                ImpulseObj02: !obj
                  TypeName: !str64 Ragdoll_Spine_1
                  UseFlag: true
                  AttackVector: !vec3 [0.0, 0.899999976, -0.815999985]
                  AttackPoint: !vec3 [0.0, 0.0, 0.0]
                  ImpulsePower: 3000.0
                ImpulseObj03: !obj
                  TypeName: !str64 ''
                  UseFlag: false
                  AttackVector: !vec3 [0.0, 0.0, 0.0]
                  AttackPoint: !vec3 [0.0, 0.0, 0.0]
                  ImpulsePower: 0.100000001
                ImpulseObj04: !obj
                  TypeName: !str64 ''
                  UseFlag: false
                  AttackVector: !vec3 [0.0, 0.0, 0.0]
                  AttackPoint: !vec3 [0.0, 0.0, 0.0]
                  ImpulsePower: 0.100000001
                ImpulseObj05: !obj
                  TypeName: !str64 ''
                  UseFlag: false
                  AttackVector: !vec3 [0.0, 0.0, 0.0]
                  AttackPoint: !vec3 [0.0, 0.0, 0.0]
                  ImpulsePower: 0.100000001
                PartImpulseData: !obj
                  IsUseReceiveImpulse: true
                  IsUseFixedImpulse: true
              lists: {}
            PartImpulseInfo02: !list
              objects:
                ReceiveObj01: !obj
                  TypeName: !str64 Ragdoll_Head
                  DivideFlag: false
                  ImpulseRate: 1.0
                  DivideRate: 0.5
                ReceiveObj02: !obj
                  TypeName: !str64 Ragdoll_Head
                  DivideFlag: false
                  ImpulseRate: 1.0
                  DivideRate: 0.5
                ReceiveObj03: !obj
                  TypeName: !str64 Ragdoll_Head
                  DivideFlag: false
                  ImpulseRate: 1.0
                  DivideRate: 0.5
                ImpulseObj01: !obj
                  TypeName: !str64 Ragdoll_Head
                  UseFlag: true
                  AttackVector: !vec3 [0.0, -1.0, -0.723999977]
                  AttackPoint: !vec3 [0.0, 0.0, 0.0]
                  ImpulsePower: 6000.0
                ImpulseObj02: !obj
                  TypeName: !str64 Ragdoll_Spine_1
                  UseFlag: true
                  AttackVector: !vec3 [0.0, -0.600000024, 1.0]
                  AttackPoint: !vec3 [0.0, 0.0, 0.0]
                  ImpulsePower: 3000.0
                ImpulseObj03: !obj
                  TypeName: !str64 ''
                  UseFlag: false
                  AttackVector: !vec3 [0.0, 0.0, 0.0]
                  AttackPoint: !vec3 [0.0, 0.0, 0.0]
                  ImpulsePower: 0.100000001
                ImpulseObj04: !obj
                  TypeName: !str64 ''
                  UseFlag: false
                  AttackVector: !vec3 [0.0, 0.0, 0.0]
                  AttackPoint: !vec3 [0.0, 0.0, 0.0]
                  ImpulsePower: 0.100000001
                ImpulseObj05: !obj
                  TypeName: !str64 ''
                  UseFlag: false
                  AttackVector: !vec3 [0.0, 0.0, 0.0]
                  AttackPoint: !vec3 [0.0, 0.0, 0.0]
                  ImpulsePower: 0.100000001
                PartImpulseData: !obj
                  IsUseReceiveImpulse: true
                  IsUseFixedImpulse: true
              lists: {}
            PartImpulseInfo03: !list
              objects:
                ReceiveObj01: !obj
                  TypeName: !str64 Ragdoll_Head
                  DivideFlag: false
                  ImpulseRate: 1.0
                  DivideRate: 0.5
                ReceiveObj02: !obj
                  TypeName: !str64 Ragdoll_Head
                  DivideFlag: false
                  ImpulseRate: 1.0
                  DivideRate: 0.5
                ReceiveObj03: !obj
                  TypeName: !str64 Ragdoll_Head
                  DivideFlag: false
                  ImpulseRate: 1.0
                  DivideRate: 0.5
                ImpulseObj01: !obj
                  TypeName: !str64 Ragdoll_Head
                  UseFlag: true
                  AttackVector: !vec3 [0.0, -1.0, -0.723999977]
                  AttackPoint: !vec3 [0.0, 0.0, 0.0]
                  ImpulsePower: 6000.0
                ImpulseObj02: !obj
                  TypeName: !str64 Ragdoll_Spine_1
                  UseFlag: true
                  AttackVector: !vec3 [0.0, -0.600000024, 1.0]
                  AttackPoint: !vec3 [0.0, 0.0, 0.0]
                  ImpulsePower: 3000.0
                ImpulseObj03: !obj
                  TypeName: !str64 ''
                  UseFlag: false
                  AttackVector: !vec3 [0.0, 0.0, 0.0]
                  AttackPoint: !vec3 [0.0, 0.0, 0.0]
                  ImpulsePower: 0.100000001
                ImpulseObj04: !obj
                  TypeName: !str64 ''
                  UseFlag: false
                  AttackVector: !vec3 [0.0, 0.0, 0.0]
                  AttackPoint: !vec3 [0.0, 0.0, 0.0]
                  ImpulsePower: 0.100000001
                ImpulseObj05: !obj
                  TypeName: !str64 ''
                  UseFlag: false
                  AttackVector: !vec3 [0.0, 0.0, 0.0]
                  AttackPoint: !vec3 [0.0, 0.0, 0.0]
                  ImpulsePower: 0.100000001
                PartImpulseData: !obj
                  IsUseReceiveImpulse: true
                  IsUseFixedImpulse: true
              lists: {}
        ImpactImpulseInfo02: !list
          objects: {}
          lists:
            PartImpulseInfo01: !list
              objects:
                ReceiveObj01: !obj
                  TypeName: !str64 Ragdoll_Head
                  DivideFlag: false
                  ImpulseRate: 1.0
                  DivideRate: 0.5
                ReceiveObj02: !obj
                  TypeName: !str64 Ragdoll_Head
                  DivideFlag: false
                  ImpulseRate: 0.600000024
                  DivideRate: 0.5
                ReceiveObj03: !obj
                  TypeName: !str64 ''
                  DivideFlag: false
                  ImpulseRate: 1.0
                  DivideRate: 0.5
                ImpulseObj01: !obj
                  TypeName: !str64 Ragdoll_Spine_1
                  UseFlag: true
                  AttackVector: !vec3 [0.0, 0.200000003, -0.518000007]
                  AttackPoint: !vec3 [0.0, 0.0, 0.0]
                  ImpulsePower: 2800.0
                ImpulseObj02: !obj
                  TypeName: !str64 ''
                  UseFlag: false
                  AttackVector: !vec3 [0.0, 0.200000003, -0.518000007]
                  AttackPoint: !vec3 [0.0, 0.0, 0.0]
                  ImpulsePower: 0.0
                ImpulseObj03: !obj
                  TypeName: !str64 ''
                  UseFlag: false
                  AttackVector: !vec3 [0.0, 0.0, 0.0]
                  AttackPoint: !vec3 [0.0, 0.0, 0.0]
                  ImpulsePower: 0.100000001
                ImpulseObj04: !obj
                  TypeName: !str64 ''
                  UseFlag: false
                  AttackVector: !vec3 [0.0, 0.0, 0.0]
                  AttackPoint: !vec3 [0.0, 0.0, 0.0]
                  ImpulsePower: 0.100000001
                ImpulseObj05: !obj
                  TypeName: !str64 ''
                  UseFlag: false
                  AttackVector: !vec3 [0.0, 0.0, 0.0]
                  AttackPoint: !vec3 [0.0, 0.0, 0.0]
                  ImpulsePower: 0.100000001
                PartImpulseData: !obj
                  IsUseReceiveImpulse: true
                  IsUseFixedImpulse: true
              lists: {}
            PartImpulseInfo02: !list
              objects:
                ReceiveObj01: !obj
                  TypeName: !str64 Ragdoll_Head
                  DivideFlag: false
                  ImpulseRate: 0.5
                  DivideRate: 0.5
                ReceiveObj02: !obj
                  TypeName: !str64 Ragdoll_Skl_Root
                  DivideFlag: false
                  ImpulseRate: 0.699999988
                  DivideRate: 0.5
                ReceiveObj03: !obj
                  TypeName: !str64 ''
                  DivideFlag: false
                  ImpulseRate: 1.0
                  DivideRate: 0.5
                ImpulseObj01: !obj
                  TypeName: !str64 Ragdoll_Spine_1
                  UseFlag: false
                  AttackVector: !vec3 [0.0, 0.291999996, -0.575999975]
                  AttackPoint: !vec3 [0.0, 0.0, 0.0]
                  ImpulsePower: 2750.0
                ImpulseObj02: !obj
                  TypeName: !str64 Ragdoll_Spine_1
                  UseFlag: true
                  AttackVector: !vec3 [0.0, 0.200000003, -0.518000007]
                  AttackPoint: !vec3 [0.0, 0.0, 0.0]
                  ImpulsePower: 2800.0
                ImpulseObj03: !obj
                  TypeName: !str64 ''
                  UseFlag: false
                  AttackVector: !vec3 [0.0, 0.0, 0.0]
                  AttackPoint: !vec3 [0.0, 0.0, 0.0]
                  ImpulsePower: 0.100000001
                ImpulseObj04: !obj
                  TypeName: !str64 ''
                  UseFlag: false
                  AttackVector: !vec3 [0.0, 0.0, 0.0]
                  AttackPoint: !vec3 [0.0, 0.0, 0.0]
                  ImpulsePower: 0.100000001
                ImpulseObj05: !obj
                  TypeName: !str64 ''
                  UseFlag: false
                  AttackVector: !vec3 [0.0, 0.0, 0.0]
                  AttackPoint: !vec3 [0.0, 0.0, 0.0]
                  ImpulsePower: 0.100000001
                PartImpulseData: !obj
                  IsUseReceiveImpulse: true
                  IsUseFixedImpulse: true
              lists: {}
            PartImpulseInfo03: !list
              objects:
                ReceiveObj01: !obj
                  TypeName: !str64 Ragdoll_Skl_Root
                  DivideFlag: false
                  ImpulseRate: 1.0
                  DivideRate: 0.5
                ReceiveObj02: !obj
                  TypeName: !str64 Ragdoll_Skl_Root
                  DivideFlag: false
                  ImpulseRate: 0.5
                  DivideRate: 0.5
                ReceiveObj03: !obj
                  TypeName: !str64 ''
                  DivideFlag: false
                  ImpulseRate: 1.0
                  DivideRate: 0.5
                ImpulseObj01: !obj
                  TypeName: !str64 Ragdoll_Spine_1
                  UseFlag: true
                  AttackVector: !vec3 [0.0, 0.105999999, -0.405999988]
                  AttackPoint: !vec3 [0.0, 0.0, 0.0]
                  ImpulsePower: 2500.0
                ImpulseObj02: !obj
                  TypeName: !str64 ''
                  UseFlag: true
                  AttackVector: !vec3 [0.0, 0.0, -0.100000001]
                  AttackPoint: !vec3 [0.0, 0.0, 0.0]
                  ImpulsePower: 0.0
                ImpulseObj03: !obj
                  TypeName: !str64 ''
                  UseFlag: false
                  AttackVector: !vec3 [0.449999988, 0.0, 0.0]
                  AttackPoint: !vec3 [0.0, 0.0, 0.0]
                  ImpulsePower: 400.0
                ImpulseObj04: !obj
                  TypeName: !str64 ''
                  UseFlag: false
                  AttackVector: !vec3 [0.0, 1.0, -0.649999976]
                  AttackPoint: !vec3 [0.0, 0.0, 0.0]
                  ImpulsePower: 400.0
                ImpulseObj05: !obj
                  TypeName: !str64 ''
                  UseFlag: false
                  AttackVector: !vec3 [0.0, 0.0, 0.0]
                  AttackPoint: !vec3 [0.0, 0.0, 0.0]
                  ImpulsePower: 0.100000001
                PartImpulseData: !obj
                  IsUseReceiveImpulse: true
                  IsUseFixedImpulse: true
              lists: {}
