!io
version: 0
type: xml
param_root: !list
  objects: {}
  lists:
    ConfigRoot: !list
      objects:
        AttackTypeImpulseData: !obj
          ImpulseUseRate: 0.5
          ImpulsePower: 1200.0
          LargeAttackRate: 3.0
          BlastOffAttackRateSmall: 3.0
          BlastOffAttackRateLarge: 3.0
          SpecialAttackRate: 4.0
      lists:
        ImpactImpulseInfo01: !list
          objects: {}
          lists:
            PartImpulseInfo01: !list
              objects:
                ReceiveObj01: !obj
                  TypeName: !str64 Ragdoll_Head
                  DivideFlag: true
                  ImpulseRate: 1.0
                  DivideRate: 0.5
                ReceiveObj02: !obj
                  TypeName: !str64 Ragdoll_Head
                  DivideFlag: true
                  ImpulseRate: 0.600000024
                  DivideRate: 0.5
                ReceiveObj03: !obj
                  TypeName: !str64 ''
                  DivideFlag: false
                  ImpulseRate: 1.0
                  DivideRate: 0.5
                ImpulseObj01: !obj
                  TypeName: !str64 Ragdoll_Head
                  UseFlag: true
                  AttackVector: !vec3 [0.0, 1.0, -0.159999996]
                  AttackPoint: !vec3 [0.0, 0.0, 0.0]
                  ImpulsePower: 1500.0
                ImpulseObj02: !obj
                  TypeName: !str64 ''
                  UseFlag: false
                  AttackVector: !vec3 [0.0, 0.0, 0.0]
                  AttackPoint: !vec3 [0.0, 0.0, 0.0]
                  ImpulsePower: 0.0
                ImpulseObj03: !obj
                  TypeName: !str64 ''
                  UseFlag: false
                  AttackVector: !vec3 [0.0, 0.0, 0.0]
                  AttackPoint: !vec3 [0.0, 0.0, 0.0]
                  ImpulsePower: 0.100000001
                ImpulseObj04: !obj
                  TypeName: !str64 ''
                  UseFlag: false
                  AttackVector: !vec3 [0.0, 0.0, 0.0]
                  AttackPoint: !vec3 [0.0, 0.0, 0.0]
                  ImpulsePower: 0.100000001
                ImpulseObj05: !obj
                  TypeName: !str64 ''
                  UseFlag: false
                  AttackVector: !vec3 [0.0, 0.0, 0.0]
                  AttackPoint: !vec3 [0.0, 0.0, 0.0]
                  ImpulsePower: 0.100000001
                PartImpulseData: !obj
                  IsUseReceiveImpulse: true
                  IsUseFixedImpulse: true
              lists: {}
            PartImpulseInfo02: !list
              objects:
                ReceiveObj01: !obj
                  TypeName: !str64 Ragdoll_Skl_Root
                  DivideFlag: true
                  ImpulseRate: 1.0
                  DivideRate: 0.5
                ReceiveObj02: !obj
                  TypeName: !str64 Ragdoll_Spine_1
                  DivideFlag: true
                  ImpulseRate: 1.0
                  DivideRate: 0.5
                ReceiveObj03: !obj
                  TypeName: !str64 Ragdoll_Head
                  DivideFlag: true
                  ImpulseRate: 1.0
                  DivideRate: 0.5
                ImpulseObj01: !obj
                  TypeName: !str64 Ragdoll_Spine_2
                  UseFlag: true
                  AttackVector: !vec3 [0.0, -0.122000001, 1.0]
                  AttackPoint: !vec3 [0.0, 0.0, 0.0]
                  ImpulsePower: 3000.0
                ImpulseObj02: !obj
                  TypeName: !str64 Ragdoll_Head
                  UseFlag: true
                  AttackVector: !vec3 [0.0, -0.800000012, -0.150000006]
                  AttackPoint: !vec3 [0.0, 0.0, 0.0]
                  ImpulsePower: 2000.0
                ImpulseObj03: !obj
                  TypeName: !str64 ''
                  UseFlag: false
                  AttackVector: !vec3 [0.0500000007, 0.0, 1.0]
                  AttackPoint: !vec3 [0.0, 0.0, 0.0]
                  ImpulsePower: 0.0
                ImpulseObj04: !obj
                  TypeName: !str64 ''
                  UseFlag: false
                  AttackVector: !vec3 [-0.0500000007, 0.0, 1.0]
                  AttackPoint: !vec3 [0.0, 0.0, 0.0]
                  ImpulsePower: 0.0
                ImpulseObj05: !obj
                  TypeName: !str64 ''
                  UseFlag: false
                  AttackVector: !vec3 [0.0, 0.0, 0.0]
                  AttackPoint: !vec3 [0.0, 0.0, 0.0]
                  ImpulsePower: 0.100000001
                PartImpulseData: !obj
                  IsUseReceiveImpulse: true
                  IsUseFixedImpulse: true
              lists: {}
            PartImpulseInfo03: !list
              objects:
                ReceiveObj01: !obj
                  TypeName: !str64 Ragdoll_Head
                  DivideFlag: false
                  ImpulseRate: 1.0
                  DivideRate: 0.5
                ReceiveObj02: !obj
                  TypeName: !str64 Ragdoll_Head
                  DivideFlag: false
                  ImpulseRate: 1.0
                  DivideRate: 0.5
                ReceiveObj03: !obj
                  TypeName: !str64 ''
                  DivideFlag: false
                  ImpulseRate: 1.0
                  DivideRate: 0.5
                ImpulseObj01: !obj
                  TypeName: !str64 Ragdoll_Spine_1
                  UseFlag: true
                  AttackVector: !vec3 [0.0, -1.0, -1.0]
                  AttackPoint: !vec3 [0.0, 0.0, 0.0]
                  ImpulsePower: 3000.0
                ImpulseObj02: !obj
                  TypeName: !str64 ''
                  UseFlag: false
                  AttackVector: !vec3 [-1.0, 0.151999995, -0.0920000002]
                  AttackPoint: !vec3 [0.0, 0.0, 0.0]
                  ImpulsePower: 300.0
                ImpulseObj03: !obj
                  TypeName: !str64 ''
                  UseFlag: false
                  AttackVector: !vec3 [0.0, 1.0, 0.349999994]
                  AttackPoint: !vec3 [0.0, 0.0, 0.0]
                  ImpulsePower: 3000.0
                ImpulseObj04: !obj
                  TypeName: !str64 ''
                  UseFlag: false
                  AttackVector: !vec3 [0.0, 1.0, -0.162]
                  AttackPoint: !vec3 [0.0, 0.0, 0.0]
                  ImpulsePower: 800.0
                ImpulseObj05: !obj
                  TypeName: !str64 ''
                  UseFlag: false
                  AttackVector: !vec3 [0.0, 0.0, 0.0]
                  AttackPoint: !vec3 [0.0, 0.0, 0.0]
                  ImpulsePower: 0.100000001
                PartImpulseData: !obj
                  IsUseReceiveImpulse: true
                  IsUseFixedImpulse: true
              lists: {}
        ImpactImpulseInfo02: !list
          objects: {}
          lists:
            PartImpulseInfo01: !list
              objects:
                ReceiveObj01: !obj
                  TypeName: !str64 Ragdoll_Head
                  DivideFlag: true
                  ImpulseRate: 1.0
                  DivideRate: 0.5
                ReceiveObj02: !obj
                  TypeName: !str64 Ragdoll_Head
                  DivideFlag: false
                  ImpulseRate: 1.0
                  DivideRate: 1.0
                ReceiveObj03: !obj
                  TypeName: !str64 Ragdoll_Skl_Root
                  DivideFlag: false
                  ImpulseRate: 1.0
                  DivideRate: 0.5
                ImpulseObj01: !obj
                  TypeName: !str64 ''
                  UseFlag: false
                  AttackVector: !vec3 [0.0, 1.0, 0.131999999]
                  AttackPoint: !vec3 [0.0, 0.200000003, 0.0]
                  ImpulsePower: 3000.0
                ImpulseObj02: !obj
                  TypeName: !str64 Ragdoll_Skl_Root
                  UseFlag: true
                  AttackVector: !vec3 [0.0, 0.713999987, -1.0]
                  AttackPoint: !vec3 [0.0, 0.0, 0.0]
                  ImpulsePower: 4500.0
                ImpulseObj03: !obj
                  TypeName: !str64 ''
                  UseFlag: false
                  AttackVector: !vec3 [0.0, 0.0, 0.0]
                  AttackPoint: !vec3 [0.0, 0.0, 0.0]
                  ImpulsePower: 0.100000001
                ImpulseObj04: !obj
                  TypeName: !str64 ''
                  UseFlag: false
                  AttackVector: !vec3 [0.0, 0.0, 0.0]
                  AttackPoint: !vec3 [0.0, 0.0, 0.0]
                  ImpulsePower: 0.100000001
                ImpulseObj05: !obj
                  TypeName: !str64 ''
                  UseFlag: false
                  AttackVector: !vec3 [0.0, 0.0, 0.0]
                  AttackPoint: !vec3 [0.0, 0.0, 0.0]
                  ImpulsePower: 0.100000001
                PartImpulseData: !obj
                  IsUseReceiveImpulse: true
                  IsUseFixedImpulse: true
              lists: {}
            PartImpulseInfo02: !list
              objects:
                ReceiveObj01: !obj
                  TypeName: !str64 Ragdoll_Spine_1
                  DivideFlag: true
                  ImpulseRate: 1.0
                  DivideRate: 0.5
                ReceiveObj02: !obj
                  TypeName: !str64 Ragdoll_Spine_1
                  DivideFlag: false
                  ImpulseRate: 1.0
                  DivideRate: 0.5
                ReceiveObj03: !obj
                  TypeName: !str64 Ragdoll_Spine_1
                  DivideFlag: false
                  ImpulseRate: 1.0
                  DivideRate: 0.5
                ImpulseObj01: !obj
                  TypeName: !str64 Ragdoll_Spine_2
                  UseFlag: true
                  AttackVector: !vec3 [0.0, 0.300000012, -0.300000012]
                  AttackPoint: !vec3 [0.0, 0.0, 0.0]
                  ImpulsePower: 6000.0
                ImpulseObj02: !obj
                  TypeName: !str64 Ragdoll_Head
                  UseFlag: true
                  AttackVector: !vec3 [0.0, -1.0, 1.0]
                  AttackPoint: !vec3 [0.0, 0.0, 0.0]
                  ImpulsePower: 1000.0
                ImpulseObj03: !obj
                  TypeName: !str64 ''
                  UseFlag: false
                  AttackVector: !vec3 [0.0500000007, 0.0, 1.0]
                  AttackPoint: !vec3 [0.0, 0.0, 0.0]
                  ImpulsePower: 250.0
                ImpulseObj04: !obj
                  TypeName: !str64 ''
                  UseFlag: false
                  AttackVector: !vec3 [-0.0500000007, 0.0, 1.0]
                  AttackPoint: !vec3 [0.0, 0.0, 0.0]
                  ImpulsePower: 250.0
                ImpulseObj05: !obj
                  TypeName: !str64 ''
                  UseFlag: false
                  AttackVector: !vec3 [0.0, 0.0, 0.0]
                  AttackPoint: !vec3 [0.0, 0.0, 0.0]
                  ImpulsePower: 0.100000001
                PartImpulseData: !obj
                  IsUseReceiveImpulse: true
                  IsUseFixedImpulse: true
              lists: {}
            PartImpulseInfo03: !list
              objects:
                ReceiveObj01: !obj
                  TypeName: !str64 Ragdoll_Leg_2_R
                  DivideFlag: true
                  ImpulseRate: 0.649999976
                  DivideRate: 0.5
                ReceiveObj02: !obj
                  TypeName: !str64 Ragdoll_Leg_2_L
                  DivideFlag: true
                  ImpulseRate: 0.649999976
                  DivideRate: 0.5
                ReceiveObj03: !obj
                  TypeName: !str64 Ragdoll_Skl_Root
                  DivideFlag: false
                  ImpulseRate: 1.0
                  DivideRate: 0.5
                ImpulseObj01: !obj
                  TypeName: !str64 Ragdoll_Leg_2_L
                  UseFlag: true
                  AttackVector: !vec3 [0.0, 0.0, -0.100000001]
                  AttackPoint: !vec3 [0.0, 0.0, 0.0]
                  ImpulsePower: 300.0
                ImpulseObj02: !obj
                  TypeName: !str64 Ragdoll_Leg_2_R
                  UseFlag: true
                  AttackVector: !vec3 [0.0, 0.0, -0.100000001]
                  AttackPoint: !vec3 [0.0, 0.0, 0.0]
                  ImpulsePower: 300.0
                ImpulseObj03: !obj
                  TypeName: !str64 Ragdoll_Spine_1
                  UseFlag: true
                  AttackVector: !vec3 [0.0, -0.252000004, -1.0]
                  AttackPoint: !vec3 [0.0, 0.0, 0.0]
                  ImpulsePower: 4000.0
                ImpulseObj04: !obj
                  TypeName: !str64 Ragdoll_Spine_1
                  UseFlag: false
                  AttackVector: !vec3 [0.0, 1.0, -0.649999976]
                  AttackPoint: !vec3 [0.0, 0.0, 0.0]
                  ImpulsePower: 400.0
                ImpulseObj05: !obj
                  TypeName: !str64 ''
                  UseFlag: false
                  AttackVector: !vec3 [0.0, 0.0, 0.0]
                  AttackPoint: !vec3 [0.0, 0.0, 0.0]
                  ImpulsePower: 0.100000001
                PartImpulseData: !obj
                  IsUseReceiveImpulse: true
                  IsUseFixedImpulse: true
              lists: {}
