!io
version: 0
type: xml
param_root: !list
  objects: {}
  lists:
    ConfigRoot: !list
      objects:
        AttackTypeImpulseData: !obj
          ImpulseUseRate: 0.600000024
          ImpulsePower: 1200.0
          LargeAttackRate: 2.0
          BlastOffAttackRateSmall: 5.0
          BlastOffAttackRateLarge: 7.0
          SpecialAttackRate: 8.0
      lists:
        ImpactImpulseInfo01: !list
          objects: {}
          lists:
            PartImpulseInfo01: !list
              objects:
                ReceiveObj01: !obj
                  TypeName: !str64 Ragdoll_Head
                  DivideFlag: false
                  ImpulseRate: 1.0
                  DivideRate: 0.5
                ReceiveObj02: !obj
                  TypeName: !str64 Ragdoll_Spine_1
                  DivideFlag: false
                  ImpulseRate: 1.0
                  DivideRate: 0.5
                ReceiveObj03: !obj
                  TypeName: !str64 Ragdoll_Spine_1
                  DivideFlag: false
                  ImpulseRate: 1.0
                  DivideRate: 0.5
                ImpulseObj01: !obj
                  TypeName: !str64 Ragdoll_Head
                  UseFlag: false
                  AttackVector: !vec3 [0.0, 0.699999988, -0.899999976]
                  AttackPoint: !vec3 [0.0, 0.0, 0.0]
                  ImpulsePower: 4000.0
                ImpulseObj02: !obj
                  TypeName: !str64 Ragdoll_Spine_1
                  UseFlag: true
                  AttackVector: !vec3 [0.0, 0.270000011, -1.0]
                  AttackPoint: !vec3 [0.0, 0.0, 0.0]
                  ImpulsePower: 7000.0
                ImpulseObj03: !obj
                  TypeName: !str64 ''
                  UseFlag: false
                  AttackVector: !vec3 [0.0, 0.0, 0.0]
                  AttackPoint: !vec3 [0.0, 0.0, 0.0]
                  ImpulsePower: 0.100000001
                ImpulseObj04: !obj
                  TypeName: !str64 ''
                  UseFlag: false
                  AttackVector: !vec3 [0.0, 0.0, 0.0]
                  AttackPoint: !vec3 [0.0, 0.0, 0.0]
                  ImpulsePower: 0.100000001
                ImpulseObj05: !obj
                  TypeName: !str64 ''
                  UseFlag: false
                  AttackVector: !vec3 [0.0, 0.0, 0.0]
                  AttackPoint: !vec3 [0.0, 0.0, 0.0]
                  ImpulsePower: 0.100000001
                PartImpulseData: !obj
                  IsUseReceiveImpulse: true
                  IsUseFixedImpulse: true
              lists: {}
            PartImpulseInfo02: !list
              objects:
                ReceiveObj01: !obj
                  TypeName: !str64 Ragdoll_Spine_1
                  DivideFlag: false
                  ImpulseRate: 1.0
                  DivideRate: 0.5
                ReceiveObj02: !obj
                  TypeName: !str64 Ragdoll_Spine_1
                  DivideFlag: false
                  ImpulseRate: 1.0
                  DivideRate: 0.5
                ReceiveObj03: !obj
                  TypeName: !str64 Ragdoll_Head
                  DivideFlag: false
                  ImpulseRate: 1.0
                  DivideRate: 0.5
                ImpulseObj01: !obj
                  TypeName: !str64 ''
                  UseFlag: false
                  AttackVector: !vec3 [0.0, 0.699999988, -0.899999976]
                  AttackPoint: !vec3 [0.0, 0.0, 0.0]
                  ImpulsePower: 5000.0
                ImpulseObj02: !obj
                  TypeName: !str64 Ragdoll_Spine_1
                  UseFlag: true
                  AttackVector: !vec3 [0.0, 0.0359999985, -0.980000019]
                  AttackPoint: !vec3 [0.0, 0.0, 0.0]
                  ImpulsePower: 10000.0
                ImpulseObj03: !obj
                  TypeName: !str64 Ragdoll_Skl_Root
                  UseFlag: true
                  AttackVector: !vec3 [0.0, -0.115999997, -1.0]
                  AttackPoint: !vec3 [0.0, 0.0, 0.0]
                  ImpulsePower: 6000.0
                ImpulseObj04: !obj
                  TypeName: !str64 ''
                  UseFlag: false
                  AttackVector: !vec3 [0.0, 0.0, 0.0]
                  AttackPoint: !vec3 [0.0, 0.0, 0.0]
                  ImpulsePower: 0.100000001
                ImpulseObj05: !obj
                  TypeName: !str64 ''
                  UseFlag: false
                  AttackVector: !vec3 [0.0, 0.0, 0.0]
                  AttackPoint: !vec3 [0.0, 0.0, 0.0]
                  ImpulsePower: 0.100000001
                PartImpulseData: !obj
                  IsUseReceiveImpulse: true
                  IsUseFixedImpulse: true
              lists: {}
            PartImpulseInfo03: !list
              objects:
                ReceiveObj01: !obj
                  TypeName: !str64 Ragdoll_Spine_1
                  DivideFlag: false
                  ImpulseRate: 1.0
                  DivideRate: 0.5
                ReceiveObj02: !obj
                  TypeName: !str64 Ragdoll_Spine_1
                  DivideFlag: false
                  ImpulseRate: 1.0
                  DivideRate: 1.0
                ReceiveObj03: !obj
                  TypeName: !str64 Ragdoll_Spine_1
                  DivideFlag: false
                  ImpulseRate: 1.0
                  DivideRate: 0.5
                ImpulseObj01: !obj
                  TypeName: !str64 Ragdoll_Skl_Root
                  UseFlag: true
                  AttackVector: !vec3 [0.0, -1.0, 0.0]
                  AttackPoint: !vec3 [0.0, 0.0, 0.0]
                  ImpulsePower: 8000.0
                ImpulseObj02: !obj
                  TypeName: !str64 ''
                  UseFlag: false
                  AttackVector: !vec3 [-1.0, 0.151999995, -0.0920000002]
                  AttackPoint: !vec3 [0.0, 0.0, 0.0]
                  ImpulsePower: 300.0
                ImpulseObj03: !obj
                  TypeName: !str64 Ragdoll_Spine_1
                  UseFlag: true
                  AttackVector: !vec3 [0.0, 0.0719999969, -1.0]
                  AttackPoint: !vec3 [0.0, 0.0, 0.0]
                  ImpulsePower: 5000.0
                ImpulseObj04: !obj
                  TypeName: !str64 ''
                  UseFlag: false
                  AttackVector: !vec3 [0.0, 1.0, -0.162]
                  AttackPoint: !vec3 [0.0, 0.0, 0.0]
                  ImpulsePower: 800.0
                ImpulseObj05: !obj
                  TypeName: !str64 ''
                  UseFlag: false
                  AttackVector: !vec3 [0.0, 0.0, 0.0]
                  AttackPoint: !vec3 [0.0, 0.0, 0.0]
                  ImpulsePower: 0.100000001
                PartImpulseData: !obj
                  IsUseReceiveImpulse: true
                  IsUseFixedImpulse: true
              lists: {}
        ImpactImpulseInfo02: !list
          objects: {}
          lists:
            PartImpulseInfo01: !list
              objects:
                ReceiveObj01: !obj
                  TypeName: !str64 Ragdoll_Head
                  DivideFlag: false
                  ImpulseRate: 0.300000012
                  DivideRate: 0.200000003
                ReceiveObj02: !obj
                  TypeName: !str64 Ragdoll_Spine_1
                  DivideFlag: false
                  ImpulseRate: 1.0
                  DivideRate: 0.178000003
                ReceiveObj03: !obj
                  TypeName: !str64 Ragdoll_Skl_Root
                  DivideFlag: false
                  ImpulseRate: 1.0
                  DivideRate: 0.5
                ImpulseObj01: !obj
                  TypeName: !str64 Ragdoll_Spine_1
                  UseFlag: true
                  AttackVector: !vec3 [0.209999993, 0.0820000023, -1.0]
                  AttackPoint: !vec3 [0.0, 0.0, 0.0]
                  ImpulsePower: 2000.0
                ImpulseObj02: !obj
                  TypeName: !str64 Ragdoll_Head
                  UseFlag: false
                  AttackVector: !vec3 [0.0, 0.349999994, -0.140000001]
                  AttackPoint: !vec3 [0.0, 0.0, 0.0]
                  ImpulsePower: 1000.0
                ImpulseObj03: !obj
                  TypeName: !str64 ''
                  UseFlag: false
                  AttackVector: !vec3 [0.0500000007, 0.0, 1.0]
                  AttackPoint: !vec3 [0.0, 0.0, 0.0]
                  ImpulsePower: 250.0
                ImpulseObj04: !obj
                  TypeName: !str64 ''
                  UseFlag: false
                  AttackVector: !vec3 [0.0, 0.0, 1.0]
                  AttackPoint: !vec3 [0.0, 0.0, 0.0]
                  ImpulsePower: 250.0
                ImpulseObj05: !obj
                  TypeName: !str64 ''
                  UseFlag: false
                  AttackVector: !vec3 [0.0, 0.0, 0.0]
                  AttackPoint: !vec3 [0.0, 0.0, 0.0]
                  ImpulsePower: 0.100000001
                PartImpulseData: !obj
                  IsUseReceiveImpulse: true
                  IsUseFixedImpulse: true
              lists: {}
            PartImpulseInfo02: !list
              objects:
                ReceiveObj01: !obj
                  TypeName: !str64 Ragdoll_Skl_Root
                  DivideFlag: true
                  ImpulseRate: 1.0
                  DivideRate: 0.5
                ReceiveObj02: !obj
                  TypeName: !str64 Ragdoll_Spine_1
                  DivideFlag: true
                  ImpulseRate: 1.0
                  DivideRate: 0.5
                ReceiveObj03: !obj
                  TypeName: !str64 Ragdoll_Skl_Root
                  DivideFlag: false
                  ImpulseRate: 0.300000012
                  DivideRate: 0.200000003
                ImpulseObj01: !obj
                  TypeName: !str64 Ragdoll_Skl_Root
                  UseFlag: true
                  AttackVector: !vec3 [0.0, -0.449999988, -1.0]
                  AttackPoint: !vec3 [0.0, 0.0, 0.0]
                  ImpulsePower: 8000.0
                ImpulseObj02: !obj
                  TypeName: !str64 Ragdoll_Spine_1
                  UseFlag: true
                  AttackVector: !vec3 [0.25, -0.275999993, -1.0]
                  AttackPoint: !vec3 [0.0, 1.0, 0.0]
                  ImpulsePower: 3100.0
                ImpulseObj03: !obj
                  TypeName: !str64 ''
                  UseFlag: false
                  AttackVector: !vec3 [0.0, 1.0, -1.0]
                  AttackPoint: !vec3 [0.0, 0.0, 0.0]
                  ImpulsePower: 8000.0
                ImpulseObj04: !obj
                  TypeName: !str64 ''
                  UseFlag: false
                  AttackVector: !vec3 [0.0, 1.0, -0.370000005]
                  AttackPoint: !vec3 [0.0, 0.0, 0.0]
                  ImpulsePower: 2000.0
                ImpulseObj05: !obj
                  TypeName: !str64 ''
                  UseFlag: false
                  AttackVector: !vec3 [0.0, 0.0, 0.0]
                  AttackPoint: !vec3 [0.0, 0.0, 0.0]
                  ImpulsePower: 0.100000001
                PartImpulseData: !obj
                  IsUseReceiveImpulse: true
                  IsUseFixedImpulse: true
              lists: {}
            PartImpulseInfo03: !list
              objects:
                ReceiveObj01: !obj
                  TypeName: !str64 Ragdoll_Leg_2_L
                  DivideFlag: true
                  ImpulseRate: 0.5
                  DivideRate: 0.5
                ReceiveObj02: !obj
                  TypeName: !str64 Ragdoll_Leg_2_R
                  DivideFlag: true
                  ImpulseRate: 0.5
                  DivideRate: 0.5
                ReceiveObj03: !obj
                  TypeName: !str64 Ragdoll_Skl_Root
                  DivideFlag: false
                  ImpulseRate: 0.5
                  DivideRate: 1.0
                ImpulseObj01: !obj
                  TypeName: !str64 Ragdoll_Leg_2_L
                  UseFlag: true
                  AttackVector: !vec3 [-1.0, 0.150000006, -0.100000001]
                  AttackPoint: !vec3 [0.0, 0.0, 0.0]
                  ImpulsePower: 3000.0
                ImpulseObj02: !obj
                  TypeName: !str64 Ragdoll_Leg_2_R
                  UseFlag: true
                  AttackVector: !vec3 [-1.0, 0.150000006, -0.100000001]
                  AttackPoint: !vec3 [0.0, 0.0, 0.0]
                  ImpulsePower: 3000.0
                ImpulseObj03: !obj
                  TypeName: !str64 Ragdoll_Skl_Root
                  UseFlag: true
                  AttackVector: !vec3 [0.0, 0.600000024, -0.649999976]
                  AttackPoint: !vec3 [0.0, 0.0, 0.0]
                  ImpulsePower: 2000.0
                ImpulseObj04: !obj
                  TypeName: !str64 Ragdoll_Spine_1
                  UseFlag: true
                  AttackVector: !vec3 [0.00999999978, -0.0460000001, -0.0160000008]
                  AttackPoint: !vec3 [0.0, 2.5, 0.0]
                  ImpulsePower: 3000.0
                ImpulseObj05: !obj
                  TypeName: !str64 ''
                  UseFlag: false
                  AttackVector: !vec3 [0.0, 0.0, 0.0]
                  AttackPoint: !vec3 [0.0, 0.0, 0.0]
                  ImpulsePower: 0.100000001
                PartImpulseData: !obj
                  IsUseReceiveImpulse: true
                  IsUseFixedImpulse: true
              lists: {}
